export const PERMISSIONS = {
  MEMBER_VIEW: 'member:view',
  MEMBER_INVITE: 'member:invite',
  MEMBER_INVITE_TEACHER: 'member:invite_teacher',
  MEMBER_INVITE_STUDENT: 'member:invite_student',
  MEMBER_REMOVE: 'member:remove',
  MEMBER_MANAGE_ROLES: 'member:manage_roles',
  MEMBER_SUSPEND: 'member:suspend',
  MEMBER_EXPORT: 'member:export',

  ROLE_VIEW: 'role:view',
  ROLE_CREATE: 'role:create',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',
  ROLE_ASSIGN: 'role:assign',
  ROLE_DUPLICATE: 'role:duplicate',
  ROLE_EXPORT: 'role:export',
  ROLE_MANAGE: 'role:manage',

  TUITION_VIEW: 'tuition:view',
  TUITION_VIEW_ALL: 'tuition:view_all',
  TUITION_CREATE: 'tuition:create',
  TUITION_EDIT_OWN: 'tuition:edit_own',
  TUITION_EDIT_ALL: 'tuition:edit_all',
  TUITION_DELETE_OWN: 'tuition:delete_own',
  TUITION_DELETE_ALL: 'tuition:delete_all',
  TUITION_APPROVE: 'tuition:approve',
  TUITION_DELETE: 'tuition:delete',

  PAYMENT_VIEW_OWN: 'payment:view_own',
  PAYMENT_VIEW_ALL: 'payment:view_all',
  PAYMENT_PROCESS: 'payment:process',
  PAYMENT_REFUND: 'payment:refund',
  PAYMENT_EXPORT: 'payment:export',
  PAYMENT_CONFIGURE: 'payment:configure',
  PAYMENT_RECONCILE: 'payment:reconcile',
  PAYMENT_AUDIT: 'payment:audit',
  PAYMENT_SCHEDULE: 'payment:schedule',

  ANALYTICS_VIEW: 'analytics:view',
  ANALYTICS_VIEW_DETAILED: 'analytics:view_detailed',
  ANALYTICS_EXPORT: 'analytics:export',
  ANALYTICS_SCHEDULE_REPORTS: 'analytics:schedule_reports',
  ANALYTICS_CUSTOM_REPORTS: 'analytics:custom_reports',
  ANALYTICS_VIEW_STUDENT_METRICS: 'analytics:view_student_metrics',

  SETTINGS_VIEW: 'settings:view',
  SETTINGS_UPDATE_PROFILE: 'settings:update_profile',
  SETTINGS_UPDATE_BILLING: 'settings:update_billing',
  SETTINGS_UPDATE_FEATURES: 'settings:update_features',
  SETTINGS_MANAGE_WEBHOOKS: 'settings:manage_webhooks',
  SETTINGS_DELETE_ORG: 'settings:delete_org',
  SETTINGS_MANAGE: 'settings:manage',

  VERIFICATION_VIEW: 'verification:view',
  VERIFICATION_APPROVE_TEACHER: 'verification:approve_teacher',
  VERIFICATION_APPROVE_ORG: 'verification:approve_org',
  VERIFICATION_REJECT: 'verification:reject',
  VERIFICATION_MANAGE_DOCS: 'verification:manage_docs',
  VERIFICATION_APPROVE: 'verification:approve',

  STUDENT_VIEW: 'student:view',
  STUDENT_CREATE: 'student:create',
  STUDENT_EDIT: 'student:edit',
  STUDENT_SUSPEND: 'student:suspend',
  STUDENT_DELETE: 'student:delete',
  STUDENT_EXPORT: 'student:export',
  STUDENT_IMPORT: 'student:import',
  TUTOR_VERIFY: 'tutor:verify',

  CLASS_MANAGE: 'class:manage',
  SUBJECT_MANAGE: 'subject:manage',
  ASSIGNMENT_CREATE: 'assignment:create',
  MATERIAL_UPLOAD: 'material:upload',
  ATTENDANCE_MARK: 'attendance:mark',
  ANNOUNCEMENT_CREATE: 'announcement:create',

  AUDIT_VIEW: 'audit:view',
  AUDIT_VIEW_DETAILED: 'audit:view_detailed',
  AUDIT_EXPORT: 'audit:export',
  AUDIT_DELETE_LOGS: 'audit:delete_logs',
  AUDIT_CONFIGURE: 'audit:configure',

  SUPER_ADMIN_VIEW_USERS: 'super_admin:view_users',
  SUPER_ADMIN_MANAGE_ORGS: 'super_admin:manage_orgs',
  SUPER_ADMIN_APPROVE_VERIFICATIONS: 'super_admin:approve_verifications',
  SUPER_ADMIN_VIEW_AUDIT: 'super_admin:view_audit',
  ORG_CREATE: 'org:create',
  ORG_MANAGE: 'org:manage',
  PLATFORM_ADMIN: 'platform:admin',
};
